sudo: required
dist: trusty
language: cpp
compiler: gcc
script: cmake
before_install:
- openssl aes-256-cbc -K $encrypted_a0b50c255c59_key -iv $encrypted_a0b50c255c59_iv
  -in secret_data.txt.enc -out secret_data.txt -d
script:
- cmake ./
- make all
- timeout 10m ./travis_test secret_data.txt
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - g++-5